.TH 7I95 1 "APRIL 2021" LinuxCNC "Configuration Tool"
.SH NAME
7i95 Configuration Tool
.SH SYNOPSIS
.B 7i95
.SH DESCRIPTION
.B 7i95 creates a set of configuration files for the Mesa
7i95 card to run on LinuxCNC version 2.9 or later.
.PP
For full Documentation visit 
.I https://jethornton.github.io/7i95/
.SH BUGS
No known bugs.
.SH AUTHOR
John Thornton
