#!/usr/bin/env python3

import sys, os
from functools import partial

from PyQt5 import uic
from PyQt5.QtWidgets import (QApplication, QMainWindow, QMessageBox)

from lib7i95 import buildcombos
from lib7i95 import buildmenus
from lib7i95 import sscards
from lib7i95 import checkconfig
from lib7i95 import loadini
from lib7i95 import buildini
from lib7i95 import buildhal
from lib7i95 import buildio
from lib7i95 import buildmisc
from lib7i95 import buildss
from lib7i95 import utilities

class VersionError(QMainWindow):
	def __init__(self):
		super(VersionError, self).__init__()
		print('wrong python version')
		msgBox = QMessageBox()
		msgBox.setIcon(QMessageBox.Warning)
		msgBox.setWindowTitle('Version Error')
		msgBox.setText('Python 3.6 or newer is required.\nYour Python is {}'.format(sys.version[0:3]))
		msgBox.setStandardButtons(QMessageBox.Ok)
		msgBox.exec()
		sys.exit()

class MainWindow(QMainWindow):
	def __init__(self):
		super(MainWindow, self).__init__()
		if os.path.split(sys.argv[0])[0] == '/usr/bin':
			self.lib_path = '/usr/lib/lib7i95'
			print('Installed')
		if os.path.split(sys.argv[0])[0] == '.':
			self.lib_path = os.path.split(os.path.realpath(sys.argv[0]))[0]
			print('In Development')
		uic.loadUi(os.path.join(self.lib_path, '7i95.ui'), self)
		self.version = '0.1.0'
		self.emcVersion = '1.1'
		self.setWindowTitle(f'7i95 Configuration Tool Version {self.version}')
		self.card = {'7i95': {'joints': 6, 'inputs': 24, 'outputs': 6}}
		self.ladderOptionsList = utilities.plcOptions()
		self.axes = 0

		buildcombos.build(self)
		buildmenus.build(self)
		utilities.checks(self)
		self.setupConnections()
		#self.testing()
		# for testing
		loadini.openini(self, '/home/john/linuxcnc/configs/7i95/7i95.ini')
		self.show()

	def testing(self):
		self.configName.setText('7i95')
		self.linearUnitsCB.setCurrentIndex(1)
		self.maxLinearVel.setText('5')
		self.ipAddressCB.setCurrentIndex(1)
		self.guiCB.setCurrentIndex(1)
		self.positionOffsetCB.setCurrentIndex(1)
		self.positionFeedbackCB.setCurrentIndex(1)
		self.axisCB_0.setCurrentIndex(1)
		#utilities.pidSetDefault(self)
		self.driveCB_0.setCurrentIndex(3)
		self.scale_0.setText('1000')
		self.minLimit_0.setText('0')
		self.maxLimit_0.setText('25')
		self.maxVelocity_0.setText('5')
		self.maxAccel_0.setText('15')
		#self..setText('')

	def setupConnections(self):
		self.configName.textChanged[str].connect(partial(utilities.configNameChanged, self))
		self.spindleTypeCB.currentIndexChanged.connect(partial(utilities.spindleTypeChanged, self))
		self.ssCardCB.currentIndexChanged.connect(partial(sscards.build, self))
		self.actionOpen.triggered.connect(partial(loadini.openini, self))
		self.actionCheck.triggered.connect(partial(checkconfig.checkit, self))
		self.actionBuild.triggered.connect(self.buildfiles)
		for i in range(self.card['7i95']['joints']):
			getattr(self, f'axisCB_{i}').currentIndexChanged.connect(partial(utilities.axisChanged, self))
		for i in range(self.card['7i95']['joints']):
			getattr(self, f'scale_{i}').textChanged.connect(partial(utilities.updateAxisInfo, self))
		for i in range(self.card['7i95']['joints']):
			getattr(self, f'maxVelocity_{i}').textChanged.connect(partial(utilities.updateAxisInfo, self))
		for i in range(self.card['7i95']['joints']):
			getattr(self, f'maxAccel_{i}').textChanged.connect(partial(utilities.updateAxisInfo, self))
		for i in range(self.card['7i95']['joints']):
			getattr(self, f'pidDefault_{i}').clicked.connect(partial(utilities.pidSetDefault, self))
		self.pidDefault_s.clicked.connect(partial(utilities.pidSetDefault, self))
		for i in range(self.card['7i95']['joints']):
			getattr(self, 'driveCB_' + str(i)).currentIndexChanged.connect(partial(utilities.driveChanged, self))

	def buildfiles(self):
		if not checkconfig.checkit(self):
			self.outputPTE.appendPlainText('Build Failed')
			return
		buildini.build(self)
		buildhal.build(self)
		buildio.build(self)
		buildmisc.build(self)
		if self.ssCardCB.currentData():
			buildss.build(self)

	def errorMsg(self, text, title=None):
		msgBox = QMessageBox()
		msgBox.setIcon(QMessageBox.Warning)
		msgBox.setWindowTitle(title)
		msgBox.setText(text)
		msgBox.setStandardButtons(QMessageBox.Cancel | QMessageBox.Ok)
		returnValue = msgBox.exec()
		if returnValue == QMessageBox.Ok:
			return True
		else:
			return False


def main():
	app = QApplication(sys.argv)
	if float(sys.version[0:3]) < 3.6:
		ex = VersionError()
	else:
		ex = MainWindow()
	sys.exit(app.exec_())

if __name__ == "__main__":
	main()
